/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package copycatch;
import java.util.*;
import java.io.*;

/**
 *
 * @author Rgv
 */
public class CopyCatch extends javax.swing.JFrame {
    
    HashMap<String,Integer> hmf = new HashMap();
    String f1name=null;
    String f2name=null;
    File f1=null;
    File f2=null;
    ArrayList commons=new ArrayList();
    boolean delf1 = true;
    boolean delf2 = true;

    /**
     * Creates new form CopyCatch
     */
    public CopyCatch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL1 = new javax.swing.JLabel();
        JL2 = new javax.swing.JLabel();
        JT1 = new javax.swing.JTextField();
        JT2 = new javax.swing.JTextField();
        JB1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA1 = new javax.swing.JTextArea();
        JB2 = new javax.swing.JButton();
        JB3 = new javax.swing.JButton();
        JB4 = new javax.swing.JButton();
        JT3 = new javax.swing.JTextField();
        JB5 = new javax.swing.JButton();
        JL3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JL1.setText("Folder ONE");

        JL2.setText("Folder Two");

        JT1.setText(" Enter path of FOLDER ONE");
        JT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT1ActionPerformed(evt);
            }
        });

        JT2.setText("Enter path of FOLDER TWO");

        JB1.setText("FIND");
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });

        JTA1.setEditable(false);
        JTA1.setColumns(20);
        JTA1.setRows(5);
        jScrollPane1.setViewportView(JTA1);

        JB2.setText("DEL F1");
        JB2.setEnabled(false);
        JB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB2ActionPerformed(evt);
            }
        });

        JB3.setText("DEL F2");
        JB3.setEnabled(false);
        JB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB3ActionPerformed(evt);
            }
        });

        JB4.setText("CPY F3");
        JB4.setEnabled(false);
        JB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB4ActionPerformed(evt);
            }
        });

        JT3.setEditable(false);
        JT3.setText("Enter path of FOLDER THREE");

        JB5.setText("COPY");
        JB5.setEnabled(false);
        JB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB5ActionPerformed(evt);
            }
        });

        JL3.setText("Messages will appear here.");

        jLabel1.setText("CopyCatch - Common files detector.");

        jLabel2.setText("Made by- https://github.com/rookiecoder10");

        jLabel3.setText("Enter absolute paths of the folders.");

        jLabel4.setText("Example-");

        jLabel5.setText("d:/folder/subfolder");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(JB2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JB3)
                            .addGap(43, 43, 43)
                            .addComponent(JB4))
                        .addComponent(JB1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JT1)
                                .addComponent(JT2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1)
                        .addComponent(JT3)
                        .addComponent(JB5)
                        .addComponent(JL3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL1)
                            .addComponent(JT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL2)
                            .addComponent(JT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB2)
                    .addComponent(JB3)
                    .addComponent(JB4))
                .addGap(18, 18, 18)
                .addComponent(JT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB5)
                .addGap(29, 29, 29)
                .addComponent(JL3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT1ActionPerformed

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        // TODO add your handling code here:
        JTA1.setText(" ");
        commons.clear();
        hmf.clear();
        JB2.setEnabled(false);
        JB3.setEnabled(false);
        JB4.setEnabled(false);
        JL3.setText("Messages will appear here");
        f1name=JT1.getText();
        f2name=JT2.getText();
        if(f1name.equals(f2name))
        {
            JTA1.setText("Both are same Folders");
            return;
        }
        f1 = new File(f1name);
        f2 = new File(f2name);
        if (!f1.exists())
        {
            JTA1.setText("Folder ONE does not exist");
            return;
        }
        if (!f2.exists())
        {
            JTA1.setText("Folder TWO does not exist");
            return;
        }
        
        File[] lof1 = f1.listFiles();
        for(int i=0;i<lof1.length;i++)
        {
            if(lof1[i].isFile())
            {
                hmf.put(lof1[i].getName(),0);
            }
        }
        
        File[] lof2 = f2.listFiles();
        for(int i=0;i<lof2.length;i++)
        {
            if(hmf.containsKey(lof2[i].getName()))
            {
                hmf.put(lof2[i].getName(),1);
            }
        }
        
        for(Map.Entry e : hmf.entrySet())
        {
            if((int)e.getValue()==1)
            {
                commons.add((String)e.getKey());
            }
        }

        if(commons.isEmpty())
        {
            JTA1.setText("No common Files in both the Folders");
            return;
        }
        
        JTA1.setText("Common Files are-\n");
        
        for(int i=0;i<commons.size();i++)
	{
            JTA1.append(commons.get(i)+"\n");
	}
        JB2.setEnabled(true);
        JB3.setEnabled(true);
        JB4.setEnabled(true);
        delf1= false;
        delf2= false;
    }//GEN-LAST:event_JB1ActionPerformed

    private void JB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB2ActionPerformed
        // TODO add your handling code here:
        if(delf1==true)
        {
            JL3.setText("All Common Files already deleted from Folder 1");
            JB2.setEnabled(false);
            return;
            
        }
        delf1 = true;
        for(int i=0;i<commons.size();i++)
        {
            File f = new File(f1name+"/"+commons.get(i));
            f.delete();
	}
	JL3.setText("All common Files deleted from folder 1");
        JB2.setEnabled(false);
        if(delf1==true && delf2==true)
        {
            JB4.setEnabled(false);
            JL3.setText("All common files deleted from both the folders");
        }
    }//GEN-LAST:event_JB2ActionPerformed

    private void JB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB3ActionPerformed
        // TODO add your handling code here:
        if(delf2==true)
        {
            JL3.setText("All Common Files already deleted from Folder 2");
            JB3.setEnabled(false);
            return;
        }
        delf2= true;
        for(int i=0;i<commons.size();i++)
	{
            File f = new File(f2name+"/"+commons.get(i));
            f.delete();
	}
	JL3.setText("All common Files deleted from folder 2");
        JB3.setEnabled(false);
        if(delf1==true && delf2==true)
        {
            JB4.setEnabled(false);
            JL3.setText("All common files deleted from both the folders");
        }
    }//GEN-LAST:event_JB3ActionPerformed

    private void JB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB4ActionPerformed
        // TODO add your handling code here:
        if(delf1==true && delf2==true)
        {
            JL3.setText("Can't copy- common files deleted from both the folders");
            JB4.setEnabled(false);
            return;
        }
        JT3.setEnabled(true);
        JT3.setEditable(true);
        JB5.setEnabled(true);
        JB2.setEnabled(false);
        JB3.setEnabled(false);
    }//GEN-LAST:event_JB4ActionPerformed

    private void JB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB5ActionPerformed
        // TODO add your handling code here:
        String f3name = JT3.getText();
        File f = new File(f3name);
        if(!f.exists())
        {
            boolean status=new File(f3name).mkdir();
            if(status==false)
            {
                JL3.setText("Unable to create new folder in specified path");
                return;
            }
				 
        }
        try
        {
            if(delf1==false)
            {
                for(int i=0;i<commons.size();i++)
                {
                    f = new File(f3name+"/"+commons.get(i));
                    f.createNewFile();
                    FileOutputStream os = new FileOutputStream(f3name+"/"+commons.get(i));
                    FileInputStream is = new FileInputStream(f1name+"/"+commons.get(i));
                    int c;
                    do
                    {
                        c=is.read();
                        if(c!=-1)
                        {
                            os.write((char)c);
                        }
                    }while(c!=-1);
                    os.close();
                    is.close();
                }
            }
            else if(delf2==false)
            {
                for(int i=0;i<commons.size();i++)
                {
                    f = new File(f3name+"/"+commons.get(i));
                    f.createNewFile();
                    FileOutputStream os = new FileOutputStream(f3name+"/"+commons.get(i));
                    FileInputStream is = new FileInputStream(f2name+"/"+commons.get(i));
                    int c;
                    do
                    {
                        c=is.read();
                        if(c!=-1)
                        {
                            os.write((char)c);
                        }
                    }while(c!=-1);
                    os.close();
                    is.close();
                }
            }
        }
        catch(Exception e)
        {
            JL3.setText("Unknown error ouccurd, please contact support- "+e.getMessage());
        }
        JL3.setText("Common Files successfully copied to foleder "+f3name);
        if(delf1==false)
            JB2.setEnabled(true);
        if(delf2==false)
            JB3.setEnabled(true);
        JT3.setEditable(false);
        JT3.setEnabled(false);
        JB5.setEnabled(false);
    }//GEN-LAST:event_JB5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CopyCatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CopyCatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CopyCatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CopyCatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CopyCatch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB1;
    private javax.swing.JButton JB2;
    private javax.swing.JButton JB3;
    private javax.swing.JButton JB4;
    private javax.swing.JButton JB5;
    private javax.swing.JLabel JL1;
    private javax.swing.JLabel JL2;
    private javax.swing.JLabel JL3;
    private javax.swing.JTextField JT1;
    private javax.swing.JTextField JT2;
    private javax.swing.JTextField JT3;
    private javax.swing.JTextArea JTA1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
